services:
    postgres:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: safepass1
            POSTGRES_DB: r3vids
        volumes:
            - r3vids:/var/lib/postgresql/data
    dotnet:
        image: mcr.microsoft.com/dotnet/sdk:8.0
        volumes:
            - .:/app
            - ./wwwroot:/app/wwwroot
            - /home/mymar101/.nuget/packages
        working_dir: /app
        command: >
            bash -c "apt-get update &&
                     apt-get install -y ffmpeg &&
                     if ! dotnet tool list -g | grep -q dotnet-ef; then dotnet tool install --global dotnet-ef; fi &&
                     export PATH="$PATH:/root/.dotnet/tools" &&
                     if [ ! -f /app/Data/Migrations ]; then  
                     dotnet ef database update && touch /app/Data/Migrations; fi &&
                     dotnet watch run"
        ports:
            - "5070:5070"
        depends_on:
            - postgres
        environment:
            - TZ=America/New_York
    next:
        image: node:latest
        volumes:
            - /home/mymar101/r3vids-next:/app
            - /home/mymar101/r3vids-next/node_modules
        working_dir: /app
        command: >
            bash -c "npm install &&
            npm run dev"
        ports:
            - "3000:3000"
        depends_on:
            - dotnet
volumes:
    r3vids:
    dotnet:
    nuget_cache: