// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using R3vids.Data;

#nullable disable

namespace R3vids.Data.Migrations
{
    [DbContext(typeof(VideoDbContext))]
    [Migration("20240501192844_UpdateVideoVideoStatusRelationship")]
    partial class UpdateVideoVideoStatusRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("R3vids.Models.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Duration")
                        .HasColumnType("numeric");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VideoStatusId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VideoStatusId1")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VideoStatusId2")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VideoStatusId3")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VideoStatusId1")
                        .IsUnique();

                    b.HasIndex("VideoStatusId2")
                        .IsUnique();

                    b.HasIndex("VideoStatusId3")
                        .IsUnique();

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("R3vids.Models.VideoNavigation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentVideoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PreviousVideoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RandomVideoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurrentVideoId");

                    b.HasIndex("PreviousVideoId");

                    b.HasIndex("RandomVideoId");

                    b.ToTable("VideoNavigation");
                });

            modelBuilder.Entity("R3vids.Models.VideoStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CurrentPlayTime")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsWatchLater")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastPlayed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Played")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("VideoStatus");
                });

            modelBuilder.Entity("R3vids.Models.Video", b =>
                {
                    b.HasOne("R3vids.Models.VideoStatus", null)
                        .WithOne("CurrentVideo")
                        .HasForeignKey("R3vids.Models.Video", "VideoStatusId1");

                    b.HasOne("R3vids.Models.VideoStatus", null)
                        .WithOne("PreviousVideo")
                        .HasForeignKey("R3vids.Models.Video", "VideoStatusId2");

                    b.HasOne("R3vids.Models.VideoStatus", null)
                        .WithOne("RandomVideo")
                        .HasForeignKey("R3vids.Models.Video", "VideoStatusId3");
                });

            modelBuilder.Entity("R3vids.Models.VideoNavigation", b =>
                {
                    b.HasOne("R3vids.Models.Video", "CurrentVideo")
                        .WithMany()
                        .HasForeignKey("CurrentVideoId");

                    b.HasOne("R3vids.Models.Video", "PreviousVideo")
                        .WithMany()
                        .HasForeignKey("PreviousVideoId");

                    b.HasOne("R3vids.Models.Video", "RandomVideo")
                        .WithMany()
                        .HasForeignKey("RandomVideoId");

                    b.Navigation("CurrentVideo");

                    b.Navigation("PreviousVideo");

                    b.Navigation("RandomVideo");
                });

            modelBuilder.Entity("R3vids.Models.VideoStatus", b =>
                {
                    b.HasOne("R3vids.Models.Video", "Video")
                        .WithOne("VideoStatus")
                        .HasForeignKey("R3vids.Models.VideoStatus", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("R3vids.Models.Video", b =>
                {
                    b.Navigation("VideoStatus")
                        .IsRequired();
                });

            modelBuilder.Entity("R3vids.Models.VideoStatus", b =>
                {
                    b.Navigation("CurrentVideo");

                    b.Navigation("PreviousVideo");

                    b.Navigation("RandomVideo");
                });
#pragma warning restore 612, 618
        }
    }
}
